version: "3.9"

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - /home/sbling/sbling-trip-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sbling
      - POSTGRES_DB=sbling-trip
    networks:
      - default
      - sbling-net

  gateway:
    image: sblingtrip/sbling-trip-gateway:latest
    pull_policy: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - auth
      - api
    networks:
      - default
      - sbling-net

  auth:
    image: sblingtrip/sbling-trip-auth:latest
    pull_policy: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - default
      - sbling-net
  api:
    image: sblingtrip/sbling-trip-api:latest
    pull_policy: always
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - default
      - sbling-net

networks:
  sbling-net:
    driver: bridge
